// @ts-check
const fs = require('fs');
const path = require('path');

const { tagSlug } = require('./src/utils/tags.js');

const RELATED_POSTS_PATH = path.join(__dirname, 'data', 'related-posts.json');

/**
 * Load precomputed related posts (generated by `task related_posts`).
 * @returns {Record<string, { slug: string; score: number }[]>}
 */
const loadRelatedPosts = () => {
  if (!fs.existsSync(RELATED_POSTS_PATH)) {
    console.warn(`${RELATED_POSTS_PATH} not found; run \`task related_posts\` to generate related posts.`);
    return {};
  }
  return JSON.parse(fs.readFileSync(RELATED_POSTS_PATH, 'utf8'));
};

exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      alias: {
        '@/components': path.resolve(__dirname, 'src/components'),
        '@/lib/utils': path.resolve(__dirname, 'src/lib/utils'),
      },
    },
  });
};

exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions;

  const blogPostTemplate = path.resolve(`./src/templates/BlogPost.js`);
  const tagTemplate = path.resolve(`./src/templates/Tag.js`);

  // Fetch blog posts
  const blogPostsResult = await graphql(`
    {
      allMdx(
        filter: { internal: { contentFilePath: { regex: "/content/Posts/" } } }
        sort: { fields: [frontmatter___date], order: DESC }
        limit: 1000
      ) {
        edges {
          node {
            id
            internal {
              contentFilePath
            }
            frontmatter {
              title
              date
              slug
              categories
              featuredImage {
                publicURL
              }
            }
          }
        }
      }
      allMarkdownRemark(
        filter: { fileAbsolutePath: { regex: "/content/Posts/" } }
        sort: { fields: [frontmatter___date], order: DESC }
        limit: 1000
      ) {
        edges {
          node {
            id
            frontmatter {
              title
              date
              slug
              categories
              featuredImage {
                publicURL
              }
            }
          }
        }
      }
    }
  `);

  if (blogPostsResult.errors) {
    throw blogPostsResult.errors;
  }

  const mdxPosts = blogPostsResult.data.allMdx?.edges || [];
  const markdownPosts = blogPostsResult.data.allMarkdownRemark?.edges || [];
  const posts = [...mdxPosts, ...markdownPosts];

  // Build tagMap from posts
  const tagMap = new Map();

  const addCategoriesToTagMap = (categories) => {
    categories
      .map((category) => (category ? category.trim() : ''))
      .filter(Boolean)
      .forEach((category) => {
        const slug = tagSlug(category);
        if (!slug) {
          return;
        }

        if (!tagMap.has(slug)) {
          tagMap.set(slug, {
            aliases: new Set([category]),
          });
          return;
        }

        const existing = tagMap.get(slug);
        existing.aliases.add(category);
      });
  };

  const titlesBySlug = new Map(posts.map((post) => [post.node.frontmatter.slug, post.node.frontmatter.title]));
  const storedRelated = loadRelatedPosts();
  /** @param {string} slug */
  const relatedPostsFor = (slug) =>
    (storedRelated[slug] || [])
      .filter((item) => titlesBySlug.has(item.slug))
      .map((item) => ({ slug: item.slug, title: titlesBySlug.get(item.slug), url: item.slug, score: item.score }));

  // Create blog post pages and add to tagMap
  posts.forEach((post) => {
    const isMdx = Boolean(post.node.internal?.contentFilePath);
    const pageComponent = isMdx
      ? `${blogPostTemplate}?__contentFilePath=${post.node.internal.contentFilePath}`
      : blogPostTemplate;
    let seoImage = '';
    if (post.node.frontmatter.featuredImage) {
      seoImage = post.node.frontmatter.featuredImage.publicURL;
    }

    createPage({
      path: post.node.frontmatter.slug,
      component: pageComponent,
      context: {
        id: isMdx ? post.node.id : null,
        slug: post.node.frontmatter.slug,
        seoImage: seoImage,
        relatedPosts: relatedPostsFor(post.node.frontmatter.slug),
      },
    });

    const categories = post.node.frontmatter.categories || [];
    addCategoriesToTagMap(categories);
  });

  // Create tag pages
  tagMap.forEach(({ aliases }, slug) => {
    createPage({
      path: `/tags/${slug}/`,
      component: tagTemplate,
      context: {
        tagSlug: slug,
        tagAliases: Array.from(aliases),
      },
    });
  });
};

// Need to define the type explicity to handle nullable fields
exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions;

  const typeDefs = `
    type TvYaml implements Node {
      title: String!    
      status: String!   
      tier: Float       
      year: Int         
      review: String    
    }

    type Mdx implements Node {
      frontmatter: MdxFrontmatter
      body: String
    }

    type MarkdownRemarkFrontmatter {
      title: String
      description: String
      date: Date @dateformat
      modified_date: Date @dateformat
      slug: String
      contentType: String
      categories: [String!] @default(value: [])
      featuredImage: File @fileByRelativePath
    }

    type MdxFrontmatter {
      title: String
      description: String
      date: Date @dateformat
      modified_date: Date @dateformat
      slug: String
      contentType: String
      categories: [String!] @default(value: [])
      featuredImage: File @fileByRelativePath
    }
  `;

  createTypes(typeDefs);
};
