- name: Cloudflare
  description: Domain Provider & Host for this website.

- name: Fastmail
  description: Email

- name: Apple Music
  description: Music Player

- name: Bitwarden
  description: Password Manager

- name: Github
  description: Where I store all my code.

- name: Github Action
  description: CI/CD I use to build and publish my website to my VPS.
