- name: Netlify
  description: I host this website here

- name: Github
  description: Software Repository hosting

- name: NameCheap
  description: Domain Provider

- name: Contabo
  description: VPS provider
