- name: NameCheap
  description: Domain Provider

- name: Contabo
  description: VPS provider

- name: Yandex
  description: Free email hosting for this domain.

- name: Spotify Web
  description: Music Player

- name: Bitwarden
  description: Password Manager

- name: Github
  description: Where I store all my code.

- name: Github Action
  description: CI/CD I use to build and publish my website to my VPS.
