name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Setup Nodejs
        uses: actions/setup-node@v.3.5.0
        with:
          node-version: 12.x
